#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from snusmic_pipeline.web_artifacts import ExportInputs, check_web_artifacts, export_web_artifacts


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Export static JSON artifacts for the SNUSMIC web showcase.")
    parser.add_argument(
        "--warehouse", default="data/warehouse", help="Warehouse directory with reports/prices CSVs."
    )
    parser.add_argument("--sim", default="data/sim", help="Simulation output directory.")
    parser.add_argument("--out", default="data/web", help="Output directory for web JSON artifacts.")
    parser.add_argument(
        "--extraction-quality",
        default="data/extraction_quality.json",
        help="Extraction quality JSON generated by audit-extraction.",
    )
    parser.add_argument(
        "--check", action="store_true", help="Verify required artifacts and deterministic output."
    )
    return parser


def main() -> int:
    args = build_parser().parse_args()
    inputs = ExportInputs(
        warehouse=Path(args.warehouse),
        sim=Path(args.sim),
        out=Path(args.out),
        extraction_quality=Path(args.extraction_quality),
    )
    result = check_web_artifacts(inputs) if args.check else export_web_artifacts(inputs)
    print(json.dumps(result, ensure_ascii=False, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
